import { Geist, Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
// import Card from "./components/Card";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistOswald = Oswald({
  variable: "--font-Oswald",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistOswald.variable} h-full antialiased`}
    >
      <body className={ `${geistOswald.className} ${geistOswald.variable} min-h-full flex flex-col`}>

        <Navbar></Navbar>
        <main>
          {children}
        </main>

        {/* <Card></Card> */}

        {/* <card>
          <h2 className="text-white text-center text-[100px] m-8"> welcone to my card</h2>
        </card> */}

        <Footer></Footer>
      </body>
    </html>
  );
}
