import { Geist, Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistOswald = Oswald({
  variable: "--font-Oswald",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistOswald.variable} h-full antialiased`}
    >
      <body className={ `${geistOswald.className} ${geistOswald.variable} min-h-full flex flex-col`}>

        <Navbar></Navbar>
        <main>
          {children}
        </main>

      </body>
    </html>
  );
}
